services:
  - type: web
    name: backend
    runtime: node
    plan: free
    buildCommand: cd backend && npm install
    startCommand: cd backend && node index.js
    envVars:
      - key: NODE_VERSION
        value: "18.8.2"
      - key: MONGODB_URI
        fromDatabase:
          name: morceauxc-cs
          property: mongodb+srv://aymardmb:Openmongo-75@cluster0.bnpgltz.mongodb.net/morceaux-cs?retryWrites=true&w=majority

  - type: web
    name: frontend
    runtime: node
    plan: free
    buildCommand: cd frontend && npm install && npm run build
    startCommand: cd frontend && npm start
    envVars:
      - key: NODE_VERSION
        value: "18.8.2"
      - key: REACT_APP_BACKEND_URL
        value: "your-backend-service-url"